name: sbom-generation-v1

on: issue_comment
  # release:
  #   types: [published]

jobs:
  generate-sbom:
    name: Generate SBOM
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - uses: actions/checkout@v4
      - name: Show Branch Information
        run: |
          echo "Branch Name: ${{ github.ref_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "SHA: ${{ github.sha }}"
      - name: Generate SBOM with Anchore
        id: sbom
        uses: anchore/sbom-action@v0
        with:
          output-file: sbom-anchore.spdx.json
          upload-release-assets: false
          upload-artifact: true

      - name: Generate SBOM with Microsoft SBOM Tool
        run: | 
          curl -Lo $RUNNER_TEMP/sbom-tool https://github.com/microsoft/sbom-tool/releases/latest/download/sbom-tool-linux-x64
          chmod +x $RUNNER_TEMP/sbom-tool
          $RUNNER_TEMP/sbom-tool generate -b . -bc . -pn ${{ github.repository }} -pv 1.0.0 -ps OwnerName -nsb https://sbom.mycompany.com -V Verbose
      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: _manifest/spdx_2.2

      - name: List files - Root
        run: ls -l
      - name: List files - sboms
        run: ls -l sboms
      - name: List files - _manifest
        run: ls -l _manifest
      - name: List files - _manifest/spdx_2.2
        run: ls -l _manifest/spdx_2.2

